### ISSUE TITLE
Investigate ibm sentiment analysis 

### ISSUE THREAD

**Issue by nauticalmonkey** [SentimentAnalysisInSE/issuecomments_analysis#1]

**Comment by bcdasilv** [comment]
Based on a quick look at IBM Natural Language Understanding and IBM Tone Analyzer, it seems that only the former supports sentiment polarity. Both have emotion measurement. Do you confirm that?

Also, please check how the API works in terms of request/response format, rate limit, text size (e.g., some APIs are better suited for small texts like tweets, while others work well with big texts and a minimum number of words), and how to interpret the response fields.

**Comment by bcdasilv** [comment]
Sorry, I hit the close button by mistake.

**Comment by bcdasilv** [comment]
Understand better how to interpret the sentiment score and the sentiment label.

**Comment by nauticalmonkey** [comment]
duplicate issue sentiment scores are detailed in another issue
