### ISSUE TITLE
Look for database of issue comments 

### ISSUE THREAD

**Issue by nauticalmonkey** [SentimentAnalysisInSE/issuecomments_analysis#2]

**Comment by bcdasilv** [comment]
I mentioned these options by email, but let me add here for documentation.

[The Emotional Side of Software Developers in JIRA](https://dl.acm.org/doi/pdf/10.1145/2901739.2903505?download=true)

There's a link there to the dataset. I'm not sure if they covered sentiment polarity or just emotions.

Also, there's a different dataset (smaller) on issue comments. Here you can find:
[Paper: Sentiment and Politeness Analysis Tools on Developer Discussions Are Unreliable, but so Are People](https://dl.acm.org/doi/pdf/10.1145/3194932.3194938?download=true)

**Comment by bcdasilv** [comment]
[Additional dataset built with CSC 508 students (Fall 2019)](https://github.com/rnett/sa-of-prs/)

**Comment by bcdasilv** [comment]
Download and understand the structure of the [JIRA EMOTION](https://dl.acm.org/doi/pdf/10.1145/2901739.2903505?download=true) dataset.
What is the size of the dataset?

Do the same analysis for the second one we call [MANUAL GH ISSUES](https://dl.acm.org/doi/pdf/10.1145/3194932.3194938?download=true).

And a third one called [SENTICR DATASET](https://github.com/senticr/SentiCR)

**Comment by bcdasilv** [comment]
What are the sentiment analysis approaches (e.g., ML models, or lexicon-based tools like SentiStrength-SE) they have applied to those datasets?

**Comment by nauticalmonkey** [comment]
SentiCR- used the 1600 comments that were manually labeled to train ML program. added rules fro words encountered in software engineering such as byte as well as the use of contractions.  they used 8 different algorithms and ran the test 100 times each to analyze results from the algorithms.  They use 5 lexicon based sentiment analysis tools and two ML tools to analyze the manually labeled comments. Lexicon( NLTK, NLTK Vader, Afinn, USent, SentiStrenght) ML(TextBlog, Vivekn), The comments were pure code review comments going over each comment line by line and looking at them at a purely individual standpoint not in conjunction with PR or the project.
Here is a link to the [paper](https://www.researchgate.net/publication/321257148_SentiCR_A_customized_sentiment_analysis_tool_for_code_review_interactions)

**Comment by nauticalmonkey** [comment]
JIRA EMOTION: They manually labeled 2000 comments and linked them to a larger data set that can be used for sentiment analysis. by linking the manual entries to the data set one can gage the accuracy of the analysis that they are doing. They did not run any sentiment analysis other than the manual emotion tagging of the initial comments. here is a link to the [DataSet](http://ansymore.uantwerpen.be/system/files/uploads/artefacts/alessandro/MSR16/archive3.zip)

**Comment by nauticalmonkey** [comment]
MANUAL GH ISSUES: Dataset of 589 randomly chosen comments from GitHub pull requests. these were manually annotated for the sentiment. They then used these comments to test 6 sentiment analysis tools and one politeness tool. The tools that they tested were SentiStrenght, Alchemy, NLTK, Stanford NLP, Senti4SD, SentiCR. The politeness tool that they used was Developed by Danescu-Niculescu-Mizil
Here is a possible link to their [database](https://github.com/gousiosg/pullreqs)?

**Comment by bcdasilv** [comment]
Just to document for future reference... Here's the paper that performed the most recent benchmark study on sentiment analysis tools (mostly academic tools or machine learning prototypes) using the Jira dataset. The CSV files we got from the Jira dataset was provided by the authors of this paper: (https://dl.acm.org/doi/10.1145/3196398.3196403)[https://dl.acm.org/doi/10.1145/3196398.3196403]
