### ISSUE TITLE
Calculate micro- and macro-avg

### ISSUE THREAD

**Issue by bcdasilv** [SentimentAnalysisInSE/issuecomments_analysis#23]
Let's use these metrics (micro and macro avgs) that are also used in the benchmark paper (https://arxiv.org/ftp/arxiv/papers/1803/1803.06525.pdf) (see section 4.1 and table 3)

The data you have in your spreadsheets is already enough to computer micro and macro avgs. 
https://datascience.stackexchange.com/questions/15989/micro-average-vs-macro-average-performance-in-a-multiclass-classification-settin

**Comment by hebertca18** [comment]
I calculated the micro and macro averages for each service and put them in the anylizedchart.xlsx sheet.

For reference:
- Micro-precision = True positives/(True positives+False positives)
where true positives/false positives is the sum of all true positives/false positives across all classes
- micro-Fscore = micro-precision = micro-recall

- Macro averages are the simple arithmetic mean of the precision, recall, or f-score

This site describes the average's meanings and might be useful for quantitative analysis: https://towardsdatascience.com/multi-class-metrics-made-simple-part-ii-the-f1-score-ebe8b2c2ca1

**Comment by bcdasilv** [comment]
Thanks, Chloe! I'll take a look later at that link later. 

It's important to calculate in the same way it was calculated in the benchmark study (see section 4.1 and table 3) so we can compare our results with theirs. Otherwise, we would be comparing apples with oranges. This is just a general comment. I couldn't compare now if your calculations are the same as the paper.
