### ISSUE TITLE
Json from wantson

### ISSUE THREAD

**Issue by nauticalmonkey** [SentimentAnalysisInSE/issuecomments_analysis#4]
take the settlement analysis from Watson and try and merge the manually annotated Jira comments provided in Jira emotion so that we have a clear picture. once we have the results look at ways to present the data in a graph

**Comment by bcdasilv** [comment]
https://github.com/bcdasilv/code-style-mining

**Comment by nauticalmonkey** [comment]
Json automation uploaded to github
