### ISSUE TITLE
start analysis of google

### ISSUE THREAD

**Issue by nauticalmonkey** [SentimentAnalysisInSE/issuecomments_analysis#8]

**Comment by nauticalmonkey** [comment]
How to train the model and if google splits the data for training itself or if we provide the split

**Comment by nauticalmonkey** [comment]
https://cloud.google.com/natural-language/docs/analyzing-sentiment

**Comment by bcdasilv** [comment]
Needs now to store the results on a new column in the jira.csv file

**Comment by nauticalmonkey** [comment]
Mismatch of fields in analysis CSV, check to make sure values were in the correct rows.

**Comment by nauticalmonkey** [comment]
complete dataset of google

**Comment by nauticalmonkey** [comment]
> Mismatch of fields in analysis CSV, check to make sure values were in the correct rows.

Mismatch was created from appended of the test file writing an extra 10 comments, these have been erased and the mismatch fixed
